### ISSUE TITLE
v2ct_utils.py

### ISSUE THREAD

**Issue by rleaver152** [pszemraj/vid2cleantxt#1]
For this to work,  the v2ct_utils.py  should be in the vid2cleantxt/ subfolder

**Comment by pszemraj** [comment]
Apologies for the late response - I was on holiday (same goes for the other issue). I'll do some testing on a clean venv and with a different IDE - the code works as-is in my initial testing, but it is possibly due to some PyCharm shenanigans that don't generalise well. I'll test and update later in the week.

Thanks for pointing this out!

**Comment by pszemraj** [comment]
agree, tested in a clean venv and via command line - moved the file.
