### ISSUE TITLE
Spacy

### ISSUE THREAD

**Issue by rleaver152** [pszemraj/vid2cleantxt#2]
I didn't spot an installation reference, but to get the en_core_web_sm file, you need to run  python -m spacy download en_core_web_sm

**Comment by pszemraj** [comment]
Apologies for the late response - I was on holiday (same goes for the other issue). Agree that the command needs to be run to download the model. It seems that *pipreqs* didn't catch a spaCy requirement, but I think the model is necessary due to a pySBD dependency - I will take a look through on a clean venv and then update the requirements lists, README, and code as needed (ideally, I'd prefer a small utils function to download the spaCy model if the user doesn't have it upon running _vid2cleantxt_folder.py or vid2cleantxt_single.py_).

Will take care of the testing and update this week.

**Comment by pszemraj** [comment]
you were right! I checked out [spacy's guidelines](https://spacy.io/usage/models#production) on what to include in **requirements.txt** and have now added the following:

```
spacy>=3.0.0,<4.0.0
https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.0.0/en_core_web_sm-3.0.0.tar.gz#egg=en_core_web_sm
```

I tested in a venv - let me know if you still have issues
